apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-sensors-rabbit
spec:
  source:
    git:
      url: https://github.com/garreeoke/spring-sensors-rabbit.git
      ref:
        branch: main
  serviceClaims:
    - name: broker
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: broker-claim